// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_RegisterNode_FullMethodName       = "/agent.NodeAgent/RegisterNode"
	NodeAgent_Heartbeat_FullMethodName          = "/agent.NodeAgent/Heartbeat"
	NodeAgent_ExecuteVMCommand_FullMethodName   = "/agent.NodeAgent/ExecuteVMCommand"
	NodeAgent_GetVMStatus_FullMethodName        = "/agent.NodeAgent/GetVMStatus"
	NodeAgent_StreamVMMetrics_FullMethodName    = "/agent.NodeAgent/StreamVMMetrics"
	NodeAgent_CreateSnapshot_FullMethodName     = "/agent.NodeAgent/CreateSnapshot"
	NodeAgent_ApplyNetworkConfig_FullMethodName = "/agent.NodeAgent/ApplyNetworkConfig"
	NodeAgent_StartVNCProxy_FullMethodName      = "/agent.NodeAgent/StartVNCProxy"
	NodeAgent_GetNodeInfo_FullMethodName        = "/agent.NodeAgent/GetNodeInfo"
	NodeAgent_ImportDisk_FullMethodName         = "/agent.NodeAgent/ImportDisk"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAgent is the primary service for communication between the MaburVM Panel
// and Node Agents. It handles node registration, heartbeat monitoring,
// VM lifecycle management, metrics streaming, and network configuration.
type NodeAgentClient interface {
	// RegisterNode handles initial node registration when an agent connects
	// to the panel for the first time. The panel assigns a node ID and returns
	// authentication credentials for subsequent requests.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Heartbeat establishes a bidirectional streaming connection for health
	// monitoring. Both panel and agent can send heartbeats to detect
	// connectivity issues and exchange status updates in real-time.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// ExecuteVMCommand sends VM lifecycle commands (create, start, stop, destroy)
	// to the node agent. This is a unary RPC as commands must complete
	// before returning a response.
	ExecuteVMCommand(ctx context.Context, in *VMCommandRequest, opts ...grpc.CallOption) (*VMCommandResponse, error)
	// GetVMStatus retrieves the current state of a VM including resource usage,
	// running processes, and health information.
	GetVMStatus(ctx context.Context, in *VMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error)
	// StreamVMMetrics opens a server-side streaming connection for real-time
	// VM metrics including CPU, memory, disk, and network statistics.
	StreamVMMetrics(ctx context.Context, in *VMMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMMetricsResponse], error)
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk state.
	// Can also be used to list, restore, or delete existing snapshots.
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// ApplyNetworkConfig applies TC (traffic control) and iptables rules
	// to enforce bandwidth limits, firewall rules, and network isolation.
	ApplyNetworkConfig(ctx context.Context, in *NetworkConfigRequest, opts ...grpc.CallOption) (*NetworkConfigResponse, error)
	// StartVNCProxy starts a noVNC proxy server for browser-based console access
	// to the VM. Returns connection details for the WebSocket VNC session.
	StartVNCProxy(ctx context.Context, in *VNCProxyRequest, opts ...grpc.CallOption) (*VNCProxyResponse, error)
	// GetNodeInfo retrieves detailed system information about the node including
	// OS version, kernel version, CPU info, memory, disk, and libvirt version.
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	// ImportDisk imports a disk image from a source path to the VM's storage.
	// Used for VM migration from external sources like Virtualizor.
	ImportDisk(ctx context.Context, in *DiskImportRequest, opts ...grpc.CallOption) (*DiskImportResponse, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[0], NodeAgent_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *nodeAgentClient) ExecuteVMCommand(ctx context.Context, in *VMCommandRequest, opts ...grpc.CallOption) (*VMCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMCommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ExecuteVMCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetVMStatus(ctx context.Context, in *VMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatusResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StreamVMMetrics(ctx context.Context, in *VMMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[1], NodeAgent_StreamVMMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VMMetricsRequest, VMMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamVMMetricsClient = grpc.ServerStreamingClient[VMMetricsResponse]

func (c *nodeAgentClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ApplyNetworkConfig(ctx context.Context, in *NetworkConfigRequest, opts ...grpc.CallOption) (*NetworkConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkConfigResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ApplyNetworkConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StartVNCProxy(ctx context.Context, in *VNCProxyRequest, opts ...grpc.CallOption) (*VNCProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VNCProxyResponse)
	err := c.cc.Invoke(ctx, NodeAgent_StartVNCProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ImportDisk(ctx context.Context, in *DiskImportRequest, opts ...grpc.CallOption) (*DiskImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskImportResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ImportDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
//
// NodeAgent is the primary service for communication between the MaburVM Panel
// and Node Agents. It handles node registration, heartbeat monitoring,
// VM lifecycle management, metrics streaming, and network configuration.
type NodeAgentServer interface {
	// RegisterNode handles initial node registration when an agent connects
	// to the panel for the first time. The panel assigns a node ID and returns
	// authentication credentials for subsequent requests.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Heartbeat establishes a bidirectional streaming connection for health
	// monitoring. Both panel and agent can send heartbeats to detect
	// connectivity issues and exchange status updates in real-time.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// ExecuteVMCommand sends VM lifecycle commands (create, start, stop, destroy)
	// to the node agent. This is a unary RPC as commands must complete
	// before returning a response.
	ExecuteVMCommand(context.Context, *VMCommandRequest) (*VMCommandResponse, error)
	// GetVMStatus retrieves the current state of a VM including resource usage,
	// running processes, and health information.
	GetVMStatus(context.Context, *VMStatusRequest) (*VMStatusResponse, error)
	// StreamVMMetrics opens a server-side streaming connection for real-time
	// VM metrics including CPU, memory, disk, and network statistics.
	StreamVMMetrics(*VMMetricsRequest, grpc.ServerStreamingServer[VMMetricsResponse]) error
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk state.
	// Can also be used to list, restore, or delete existing snapshots.
	CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// ApplyNetworkConfig applies TC (traffic control) and iptables rules
	// to enforce bandwidth limits, firewall rules, and network isolation.
	ApplyNetworkConfig(context.Context, *NetworkConfigRequest) (*NetworkConfigResponse, error)
	// StartVNCProxy starts a noVNC proxy server for browser-based console access
	// to the VM. Returns connection details for the WebSocket VNC session.
	StartVNCProxy(context.Context, *VNCProxyRequest) (*VNCProxyResponse, error)
	// GetNodeInfo retrieves detailed system information about the node including
	// OS version, kernel version, CPU info, memory, disk, and libvirt version.
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	// ImportDisk imports a disk image from a source path to the VM's storage.
	// Used for VM migration from external sources like Virtualizor.
	ImportDisk(context.Context, *DiskImportRequest) (*DiskImportResponse, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeAgentServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeAgentServer) ExecuteVMCommand(context.Context, *VMCommandRequest) (*VMCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteVMCommand not implemented")
}
func (UnimplementedNodeAgentServer) GetVMStatus(context.Context, *VMStatusRequest) (*VMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedNodeAgentServer) StreamVMMetrics(*VMMetricsRequest, grpc.ServerStreamingServer[VMMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamVMMetrics not implemented")
}
func (UnimplementedNodeAgentServer) CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedNodeAgentServer) ApplyNetworkConfig(context.Context, *NetworkConfigRequest) (*NetworkConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNetworkConfig not implemented")
}
func (UnimplementedNodeAgentServer) StartVNCProxy(context.Context, *VNCProxyRequest) (*VNCProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVNCProxy not implemented")
}
func (UnimplementedNodeAgentServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeAgentServer) ImportDisk(context.Context, *DiskImportRequest) (*DiskImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportDisk not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _NodeAgent_ExecuteVMCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ExecuteVMCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ExecuteVMCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ExecuteVMCommand(ctx, req.(*VMCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetVMStatus(ctx, req.(*VMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StreamVMMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VMMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).StreamVMMetrics(m, &grpc.GenericServerStream[VMMetricsRequest, VMMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamVMMetricsServer = grpc.ServerStreamingServer[VMMetricsResponse]

func _NodeAgent_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ApplyNetworkConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ApplyNetworkConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ApplyNetworkConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ApplyNetworkConfig(ctx, req.(*NetworkConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StartVNCProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VNCProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).StartVNCProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_StartVNCProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).StartVNCProxy(ctx, req.(*VNCProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ImportDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ImportDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ImportDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ImportDisk(ctx, req.(*DiskImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeAgent_RegisterNode_Handler,
		},
		{
			MethodName: "ExecuteVMCommand",
			Handler:    _NodeAgent_ExecuteVMCommand_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _NodeAgent_GetVMStatus_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _NodeAgent_CreateSnapshot_Handler,
		},
		{
			MethodName: "ApplyNetworkConfig",
			Handler:    _NodeAgent_ApplyNetworkConfig_Handler,
		},
		{
			MethodName: "StartVNCProxy",
			Handler:    _NodeAgent_StartVNCProxy_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeAgent_GetNodeInfo_Handler,
		},
		{
			MethodName: "ImportDisk",
			Handler:    _NodeAgent_ImportDisk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _NodeAgent_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamVMMetrics",
			Handler:       _NodeAgent_StreamVMMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/agent.proto",
}
