// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/proto/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_RegisterNode_FullMethodName        = "/agent.NodeAgent/RegisterNode"
	NodeAgent_Heartbeat_FullMethodName           = "/agent.NodeAgent/Heartbeat"
	NodeAgent_ExecuteVMCommand_FullMethodName    = "/agent.NodeAgent/ExecuteVMCommand"
	NodeAgent_GetVMStatus_FullMethodName         = "/agent.NodeAgent/GetVMStatus"
	NodeAgent_StreamVMMetrics_FullMethodName     = "/agent.NodeAgent/StreamVMMetrics"
	NodeAgent_CreateSnapshot_FullMethodName      = "/agent.NodeAgent/CreateSnapshot"
	NodeAgent_ApplyNetworkConfig_FullMethodName  = "/agent.NodeAgent/ApplyNetworkConfig"
	NodeAgent_StartVNCProxy_FullMethodName       = "/agent.NodeAgent/StartVNCProxy"
	NodeAgent_GetNodeInfo_FullMethodName         = "/agent.NodeAgent/GetNodeInfo"
	NodeAgent_ImportDisk_FullMethodName          = "/agent.NodeAgent/ImportDisk"
	NodeAgent_BackupDisk_FullMethodName          = "/agent.NodeAgent/BackupDisk"
	NodeAgent_RestoreDisk_FullMethodName         = "/agent.NodeAgent/RestoreDisk"
	NodeAgent_GetLiveMetrics_FullMethodName      = "/agent.NodeAgent/GetLiveMetrics"
	NodeAgent_ScanVMs_FullMethodName             = "/agent.NodeAgent/ScanVMs"
	NodeAgent_CreateStorageVolume_FullMethodName = "/agent.NodeAgent/CreateStorageVolume"
	NodeAgent_DeleteStorageVolume_FullMethodName = "/agent.NodeAgent/DeleteStorageVolume"
	NodeAgent_GetStorageReport_FullMethodName    = "/agent.NodeAgent/GetStorageReport"
	NodeAgent_MigrateVM_FullMethodName           = "/agent.NodeAgent/MigrateVM"
	NodeAgent_SyncTemplate_FullMethodName        = "/agent.NodeAgent/SyncTemplate"
	NodeAgent_AttachDisk_FullMethodName          = "/agent.NodeAgent/AttachDisk"
	NodeAgent_DetachDisk_FullMethodName          = "/agent.NodeAgent/DetachDisk"
	NodeAgent_DefineNetwork_FullMethodName       = "/agent.NodeAgent/DefineNetwork"
	NodeAgent_UndefineNetwork_FullMethodName     = "/agent.NodeAgent/UndefineNetwork"
	NodeAgent_ProbeIPs_FullMethodName            = "/agent.NodeAgent/ProbeIPs"
	NodeAgent_ConfigureFloatingIP_FullMethodName = "/agent.NodeAgent/ConfigureFloatingIP"
	NodeAgent_ConfigureVPC_FullMethodName        = "/agent.NodeAgent/ConfigureVPC"
	NodeAgent_SetQuarantine_FullMethodName       = "/agent.NodeAgent/SetQuarantine"
	NodeAgent_SetConsoleAccess_FullMethodName    = "/agent.NodeAgent/SetConsoleAccess"
	NodeAgent_GetExportProgress_FullMethodName   = "/agent.NodeAgent/GetExportProgress"
	NodeAgent_GetGuestConnections_FullMethodName = "/agent.NodeAgent/GetGuestConnections"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAgent is the primary service for communication between the MaburVM Panel
// and Node Agents. It handles node registration, heartbeat monitoring,
// VM lifecycle management, metrics streaming, and network configuration.
type NodeAgentClient interface {
	// RegisterNode handles initial node registration when an agent connects
	// to the panel for the first time. The panel assigns a node ID and returns
	// authentication credentials for subsequent requests.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Heartbeat establishes a bidirectional streaming connection for health
	// monitoring. Both panel and agent can send heartbeats to detect
	// connectivity issues and exchange status updates in real-time.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// ExecuteVMCommand sends VM lifecycle commands (create, start, stop, destroy)
	// to the node agent. This is a unary RPC as commands must complete
	// before returning a response.
	ExecuteVMCommand(ctx context.Context, in *VMCommandRequest, opts ...grpc.CallOption) (*VMCommandResponse, error)
	// GetVMStatus retrieves the current state of a VM including resource usage,
	// running processes, and health information.
	GetVMStatus(ctx context.Context, in *VMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error)
	// StreamVMMetrics opens a server-side streaming connection for real-time
	// VM metrics including CPU, memory, disk, and network statistics.
	StreamVMMetrics(ctx context.Context, in *VMMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMMetricsResponse], error)
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk state.
	// Can also be used to list, restore, or delete existing snapshots.
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// ApplyNetworkConfig applies TC (traffic control) and iptables rules
	// to enforce bandwidth limits, firewall rules, and network isolation.
	ApplyNetworkConfig(ctx context.Context, in *NetworkConfigRequest, opts ...grpc.CallOption) (*NetworkConfigResponse, error)
	// StartVNCProxy starts a noVNC proxy server for browser-based console access
	// to the VM. Returns connection details for the WebSocket VNC session.
	StartVNCProxy(ctx context.Context, in *VNCProxyRequest, opts ...grpc.CallOption) (*VNCProxyResponse, error)
	// GetNodeInfo retrieves detailed system information about the node including
	// OS version, kernel version, CPU info, memory, disk, and libvirt version.
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	// ImportDisk imports a disk image from a source path to the VM's storage.
	// Used for VM migration from external sources.
	ImportDisk(ctx context.Context, in *DiskImportRequest, opts ...grpc.CallOption) (*DiskImportResponse, error)
	// BackupDisk exports a VM's primary disk (compressed qcow2) and uploads it to
	// the node's configured object storage, returning the object key, size and
	// checksum. This is the real backup payload (not just metadata).
	BackupDisk(ctx context.Context, in *BackupDiskRequest, opts ...grpc.CallOption) (*BackupDiskResponse, error)
	// RestoreDisk downloads a previously-backed-up qcow2 from object storage,
	// verifies its SHA256, and swaps it into the VM's primary disk. The VM MUST
	// be shut off; the agent rejects the call otherwise.
	RestoreDisk(ctx context.Context, in *RestoreDiskRequest, opts ...grpc.CallOption) (*RestoreDiskResponse, error)
	// GetLiveMetrics retrieves real-time system metrics from the node including
	// CPU usage, memory usage, disk usage, network I/O, disk I/O, and load average.
	GetLiveMetrics(ctx context.Context, in *GetLiveMetricsRequest, opts ...grpc.CallOption) (*GetLiveMetricsResponse, error)
	// ScanVMs scans the node for all VMs via libvirt and returns their info for import
	ScanVMs(ctx context.Context, in *ScanVMsRequest, opts ...grpc.CallOption) (*ScanVMsResponse, error)
	// CreateStorageVolume provisions a real disk image (qcow2/raw) in a storage
	// pool directory on the node, returning its path and actual size.
	CreateStorageVolume(ctx context.Context, in *CreateStorageVolumeRequest, opts ...grpc.CallOption) (*CreateStorageVolumeResponse, error)
	// DeleteStorageVolume removes a previously provisioned volume file from the node.
	DeleteStorageVolume(ctx context.Context, in *DeleteStorageVolumeRequest, opts ...grpc.CallOption) (*DeleteStorageVolumeResponse, error)
	// GetStorageReport measures the filesystem behind each given pool path, and
	// reports where the node's domains actually keep their disks.
	//
	// Both halves exist because of the same failure: the panel used to show every
	// pool the node's ROOT filesystem usage, so a pool directory holding nothing
	// reported gigabytes in use while the volume holding every customer's disk —
	// mounted elsewhere and 76% full — was invisible. Measuring the pool's own
	// path fixes the number; reporting the disk locations is what reveals storage
	// in use that nobody registered as a pool at all.
	GetStorageReport(ctx context.Context, in *GetStorageReportRequest, opts ...grpc.CallOption) (*GetStorageReportResponse, error)
	// MigrateVM live-migrates a domain from this (source) node to a destination
	// libvirt URI using peer-to-peer migration.
	MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error)
	// SyncTemplate downloads/caches an OS template image on this node and returns
	// its local path, size and checksum (idempotent — reuses a cached copy).
	SyncTemplate(ctx context.Context, in *SyncTemplateRequest, opts ...grpc.CallOption) (*SyncTemplateResponse, error)
	// AttachDisk provisions a new data volume and hot-plugs it into a VM as the
	// next free virtio target. DetachDisk removes it (and optionally deletes it).
	AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*AttachDiskResponse, error)
	DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*DetachDiskResponse, error)
	// DefineNetwork creates+starts an isolated/NAT libvirt network (a managed
	// bridge for private VPC segments). UndefineNetwork removes it.
	DefineNetwork(ctx context.Context, in *DefineNetworkRequest, opts ...grpc.CallOption) (*DefineNetworkResponse, error)
	UndefineNetwork(ctx context.Context, in *UndefineNetworkRequest, opts ...grpc.CallOption) (*UndefineNetworkResponse, error)
	// ProbeIPs ARP-probes a set of IPs on a bridge and returns those that answer
	// (i.e. are live on the wire). The panel uses this to detect IPs already used
	// by VMs it doesn't manage (e.g. pre-existing unmanaged guests), so it never
	// allocates a live customer IP and its IPAM view reflects reality.
	ProbeIPs(ctx context.Context, in *ProbeIPsRequest, opts ...grpc.CallOption) (*ProbeIPsResponse, error)
	// ConfigureFloatingIP attaches or detaches a floating (elastic) IP on the
	// host: the address is bound to the uplink bridge and 1:1-NATed to the VM's
	// own address, so it can be moved between VMs on the node without any guest
	// cooperation. Idempotent — the panel re-applies attachments after a node
	// reboot, since iptables rules are runtime-only state.
	ConfigureFloatingIP(ctx context.Context, in *FloatingIPRequest, opts ...grpc.CallOption) (*FloatingIPResponse, error)
	// ConfigureVPC creates or removes a tenant VPC on this node: a bridge for the
	// guests plus a router network namespace holding the VPC's gateway and NAT.
	//
	// The gateway deliberately lives in a namespace rather than on the host. The
	// host has a single routing table, so two tenants using the same subnet would
	// otherwise produce two competing routes and the kernel would deliver both
	// tenants' traffic to whichever bridge came first — a cross-tenant misdelivery,
	// not merely a clash. A namespace per VPC gives each its own routing table, so
	// overlapping tenant subnets are safe.
	ConfigureVPC(ctx context.Context, in *VPCRequest, opts ...grpc.CallOption) (*VPCResponse, error)
	// SetQuarantine cuts a guest off the network, or puts it back, without
	// stopping it — the owner keeps console access and their data while the abuse
	// stops. Keyed on MAC rather than VM id because the guests that need this are
	// often ones the panel does not manage, and an abusive guest may be running a
	// spoofed or duplicated address.
	SetQuarantine(ctx context.Context, in *SetQuarantineRequest, opts ...grpc.CallOption) (*SetQuarantineResponse, error)
	// SetConsoleAccess enforces console enable/disable on the domain itself.
	//
	// The panel used to record this as a flag and nothing more, which gated its
	// own proxy while qemu carried on listening on 0.0.0.0 — so a "disabled"
	// console was still reachable by anyone who could route to the node and knew
	// the VNC password. Enforcement has to happen where the socket is.
	SetConsoleAccess(ctx context.Context, in *SetConsoleAccessRequest, opts ...grpc.CallOption) (*SetConsoleAccessResponse, error)
	// GetExportProgress reports the disk exports running on this node right now.
	//
	// A compressed export of a large disk takes hours, during which the panel
	// showed only "pending" — indistinguishable from a job that had never
	// started, and from one that was stuck. Operators were left guessing whether
	// to wait or to intervene.
	GetExportProgress(ctx context.Context, in *GetExportProgressRequest, opts ...grpc.CallOption) (*GetExportProgressResponse, error)
	// GetGuestConnections reports how fast each guest on this node is opening new
	// outbound connections. Bandwidth cannot answer that question: a port scan is
	// enormous in packets and connections but trivial in bytes, so traffic graphs
	// stay flat while the node's conntrack table fills and every tenant on it
	// loses connectivity.
	GetGuestConnections(ctx context.Context, in *GetGuestConnectionsRequest, opts ...grpc.CallOption) (*GetGuestConnectionsResponse, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[0], NodeAgent_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *nodeAgentClient) ExecuteVMCommand(ctx context.Context, in *VMCommandRequest, opts ...grpc.CallOption) (*VMCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMCommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ExecuteVMCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetVMStatus(ctx context.Context, in *VMStatusRequest, opts ...grpc.CallOption) (*VMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatusResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StreamVMMetrics(ctx context.Context, in *VMMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[1], NodeAgent_StreamVMMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VMMetricsRequest, VMMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamVMMetricsClient = grpc.ServerStreamingClient[VMMetricsResponse]

func (c *nodeAgentClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ApplyNetworkConfig(ctx context.Context, in *NetworkConfigRequest, opts ...grpc.CallOption) (*NetworkConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkConfigResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ApplyNetworkConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StartVNCProxy(ctx context.Context, in *VNCProxyRequest, opts ...grpc.CallOption) (*VNCProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VNCProxyResponse)
	err := c.cc.Invoke(ctx, NodeAgent_StartVNCProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ImportDisk(ctx context.Context, in *DiskImportRequest, opts ...grpc.CallOption) (*DiskImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskImportResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ImportDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) BackupDisk(ctx context.Context, in *BackupDiskRequest, opts ...grpc.CallOption) (*BackupDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupDiskResponse)
	err := c.cc.Invoke(ctx, NodeAgent_BackupDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) RestoreDisk(ctx context.Context, in *RestoreDiskRequest, opts ...grpc.CallOption) (*RestoreDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreDiskResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RestoreDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetLiveMetrics(ctx context.Context, in *GetLiveMetricsRequest, opts ...grpc.CallOption) (*GetLiveMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiveMetricsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetLiveMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ScanVMs(ctx context.Context, in *ScanVMsRequest, opts ...grpc.CallOption) (*ScanVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanVMsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ScanVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) CreateStorageVolume(ctx context.Context, in *CreateStorageVolumeRequest, opts ...grpc.CallOption) (*CreateStorageVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStorageVolumeResponse)
	err := c.cc.Invoke(ctx, NodeAgent_CreateStorageVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DeleteStorageVolume(ctx context.Context, in *DeleteStorageVolumeRequest, opts ...grpc.CallOption) (*DeleteStorageVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStorageVolumeResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DeleteStorageVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetStorageReport(ctx context.Context, in *GetStorageReportRequest, opts ...grpc.CallOption) (*GetStorageReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageReportResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetStorageReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateVMResponse)
	err := c.cc.Invoke(ctx, NodeAgent_MigrateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) SyncTemplate(ctx context.Context, in *SyncTemplateRequest, opts ...grpc.CallOption) (*SyncTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncTemplateResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SyncTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) AttachDisk(ctx context.Context, in *AttachDiskRequest, opts ...grpc.CallOption) (*AttachDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachDiskResponse)
	err := c.cc.Invoke(ctx, NodeAgent_AttachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DetachDisk(ctx context.Context, in *DetachDiskRequest, opts ...grpc.CallOption) (*DetachDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachDiskResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DetachDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) DefineNetwork(ctx context.Context, in *DefineNetworkRequest, opts ...grpc.CallOption) (*DefineNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefineNetworkResponse)
	err := c.cc.Invoke(ctx, NodeAgent_DefineNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UndefineNetwork(ctx context.Context, in *UndefineNetworkRequest, opts ...grpc.CallOption) (*UndefineNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndefineNetworkResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UndefineNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ProbeIPs(ctx context.Context, in *ProbeIPsRequest, opts ...grpc.CallOption) (*ProbeIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeIPsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ProbeIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ConfigureFloatingIP(ctx context.Context, in *FloatingIPRequest, opts ...grpc.CallOption) (*FloatingIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloatingIPResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ConfigureFloatingIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ConfigureVPC(ctx context.Context, in *VPCRequest, opts ...grpc.CallOption) (*VPCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VPCResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ConfigureVPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) SetQuarantine(ctx context.Context, in *SetQuarantineRequest, opts ...grpc.CallOption) (*SetQuarantineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetQuarantineResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SetQuarantine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) SetConsoleAccess(ctx context.Context, in *SetConsoleAccessRequest, opts ...grpc.CallOption) (*SetConsoleAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConsoleAccessResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SetConsoleAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetExportProgress(ctx context.Context, in *GetExportProgressRequest, opts ...grpc.CallOption) (*GetExportProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportProgressResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetExportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetGuestConnections(ctx context.Context, in *GetGuestConnectionsRequest, opts ...grpc.CallOption) (*GetGuestConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGuestConnectionsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetGuestConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
//
// NodeAgent is the primary service for communication between the MaburVM Panel
// and Node Agents. It handles node registration, heartbeat monitoring,
// VM lifecycle management, metrics streaming, and network configuration.
type NodeAgentServer interface {
	// RegisterNode handles initial node registration when an agent connects
	// to the panel for the first time. The panel assigns a node ID and returns
	// authentication credentials for subsequent requests.
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Heartbeat establishes a bidirectional streaming connection for health
	// monitoring. Both panel and agent can send heartbeats to detect
	// connectivity issues and exchange status updates in real-time.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// ExecuteVMCommand sends VM lifecycle commands (create, start, stop, destroy)
	// to the node agent. This is a unary RPC as commands must complete
	// before returning a response.
	ExecuteVMCommand(context.Context, *VMCommandRequest) (*VMCommandResponse, error)
	// GetVMStatus retrieves the current state of a VM including resource usage,
	// running processes, and health information.
	GetVMStatus(context.Context, *VMStatusRequest) (*VMStatusResponse, error)
	// StreamVMMetrics opens a server-side streaming connection for real-time
	// VM metrics including CPU, memory, disk, and network statistics.
	StreamVMMetrics(*VMMetricsRequest, grpc.ServerStreamingServer[VMMetricsResponse]) error
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk state.
	// Can also be used to list, restore, or delete existing snapshots.
	CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// ApplyNetworkConfig applies TC (traffic control) and iptables rules
	// to enforce bandwidth limits, firewall rules, and network isolation.
	ApplyNetworkConfig(context.Context, *NetworkConfigRequest) (*NetworkConfigResponse, error)
	// StartVNCProxy starts a noVNC proxy server for browser-based console access
	// to the VM. Returns connection details for the WebSocket VNC session.
	StartVNCProxy(context.Context, *VNCProxyRequest) (*VNCProxyResponse, error)
	// GetNodeInfo retrieves detailed system information about the node including
	// OS version, kernel version, CPU info, memory, disk, and libvirt version.
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	// ImportDisk imports a disk image from a source path to the VM's storage.
	// Used for VM migration from external sources.
	ImportDisk(context.Context, *DiskImportRequest) (*DiskImportResponse, error)
	// BackupDisk exports a VM's primary disk (compressed qcow2) and uploads it to
	// the node's configured object storage, returning the object key, size and
	// checksum. This is the real backup payload (not just metadata).
	BackupDisk(context.Context, *BackupDiskRequest) (*BackupDiskResponse, error)
	// RestoreDisk downloads a previously-backed-up qcow2 from object storage,
	// verifies its SHA256, and swaps it into the VM's primary disk. The VM MUST
	// be shut off; the agent rejects the call otherwise.
	RestoreDisk(context.Context, *RestoreDiskRequest) (*RestoreDiskResponse, error)
	// GetLiveMetrics retrieves real-time system metrics from the node including
	// CPU usage, memory usage, disk usage, network I/O, disk I/O, and load average.
	GetLiveMetrics(context.Context, *GetLiveMetricsRequest) (*GetLiveMetricsResponse, error)
	// ScanVMs scans the node for all VMs via libvirt and returns their info for import
	ScanVMs(context.Context, *ScanVMsRequest) (*ScanVMsResponse, error)
	// CreateStorageVolume provisions a real disk image (qcow2/raw) in a storage
	// pool directory on the node, returning its path and actual size.
	CreateStorageVolume(context.Context, *CreateStorageVolumeRequest) (*CreateStorageVolumeResponse, error)
	// DeleteStorageVolume removes a previously provisioned volume file from the node.
	DeleteStorageVolume(context.Context, *DeleteStorageVolumeRequest) (*DeleteStorageVolumeResponse, error)
	// GetStorageReport measures the filesystem behind each given pool path, and
	// reports where the node's domains actually keep their disks.
	//
	// Both halves exist because of the same failure: the panel used to show every
	// pool the node's ROOT filesystem usage, so a pool directory holding nothing
	// reported gigabytes in use while the volume holding every customer's disk —
	// mounted elsewhere and 76% full — was invisible. Measuring the pool's own
	// path fixes the number; reporting the disk locations is what reveals storage
	// in use that nobody registered as a pool at all.
	GetStorageReport(context.Context, *GetStorageReportRequest) (*GetStorageReportResponse, error)
	// MigrateVM live-migrates a domain from this (source) node to a destination
	// libvirt URI using peer-to-peer migration.
	MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error)
	// SyncTemplate downloads/caches an OS template image on this node and returns
	// its local path, size and checksum (idempotent — reuses a cached copy).
	SyncTemplate(context.Context, *SyncTemplateRequest) (*SyncTemplateResponse, error)
	// AttachDisk provisions a new data volume and hot-plugs it into a VM as the
	// next free virtio target. DetachDisk removes it (and optionally deletes it).
	AttachDisk(context.Context, *AttachDiskRequest) (*AttachDiskResponse, error)
	DetachDisk(context.Context, *DetachDiskRequest) (*DetachDiskResponse, error)
	// DefineNetwork creates+starts an isolated/NAT libvirt network (a managed
	// bridge for private VPC segments). UndefineNetwork removes it.
	DefineNetwork(context.Context, *DefineNetworkRequest) (*DefineNetworkResponse, error)
	UndefineNetwork(context.Context, *UndefineNetworkRequest) (*UndefineNetworkResponse, error)
	// ProbeIPs ARP-probes a set of IPs on a bridge and returns those that answer
	// (i.e. are live on the wire). The panel uses this to detect IPs already used
	// by VMs it doesn't manage (e.g. pre-existing unmanaged guests), so it never
	// allocates a live customer IP and its IPAM view reflects reality.
	ProbeIPs(context.Context, *ProbeIPsRequest) (*ProbeIPsResponse, error)
	// ConfigureFloatingIP attaches or detaches a floating (elastic) IP on the
	// host: the address is bound to the uplink bridge and 1:1-NATed to the VM's
	// own address, so it can be moved between VMs on the node without any guest
	// cooperation. Idempotent — the panel re-applies attachments after a node
	// reboot, since iptables rules are runtime-only state.
	ConfigureFloatingIP(context.Context, *FloatingIPRequest) (*FloatingIPResponse, error)
	// ConfigureVPC creates or removes a tenant VPC on this node: a bridge for the
	// guests plus a router network namespace holding the VPC's gateway and NAT.
	//
	// The gateway deliberately lives in a namespace rather than on the host. The
	// host has a single routing table, so two tenants using the same subnet would
	// otherwise produce two competing routes and the kernel would deliver both
	// tenants' traffic to whichever bridge came first — a cross-tenant misdelivery,
	// not merely a clash. A namespace per VPC gives each its own routing table, so
	// overlapping tenant subnets are safe.
	ConfigureVPC(context.Context, *VPCRequest) (*VPCResponse, error)
	// SetQuarantine cuts a guest off the network, or puts it back, without
	// stopping it — the owner keeps console access and their data while the abuse
	// stops. Keyed on MAC rather than VM id because the guests that need this are
	// often ones the panel does not manage, and an abusive guest may be running a
	// spoofed or duplicated address.
	SetQuarantine(context.Context, *SetQuarantineRequest) (*SetQuarantineResponse, error)
	// SetConsoleAccess enforces console enable/disable on the domain itself.
	//
	// The panel used to record this as a flag and nothing more, which gated its
	// own proxy while qemu carried on listening on 0.0.0.0 — so a "disabled"
	// console was still reachable by anyone who could route to the node and knew
	// the VNC password. Enforcement has to happen where the socket is.
	SetConsoleAccess(context.Context, *SetConsoleAccessRequest) (*SetConsoleAccessResponse, error)
	// GetExportProgress reports the disk exports running on this node right now.
	//
	// A compressed export of a large disk takes hours, during which the panel
	// showed only "pending" — indistinguishable from a job that had never
	// started, and from one that was stuck. Operators were left guessing whether
	// to wait or to intervene.
	GetExportProgress(context.Context, *GetExportProgressRequest) (*GetExportProgressResponse, error)
	// GetGuestConnections reports how fast each guest on this node is opening new
	// outbound connections. Bandwidth cannot answer that question: a port scan is
	// enormous in packets and connections but trivial in bytes, so traffic graphs
	// stay flat while the node's conntrack table fills and every tenant on it
	// loses connectivity.
	GetGuestConnections(context.Context, *GetGuestConnectionsRequest) (*GetGuestConnectionsResponse, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeAgentServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeAgentServer) ExecuteVMCommand(context.Context, *VMCommandRequest) (*VMCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteVMCommand not implemented")
}
func (UnimplementedNodeAgentServer) GetVMStatus(context.Context, *VMStatusRequest) (*VMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedNodeAgentServer) StreamVMMetrics(*VMMetricsRequest, grpc.ServerStreamingServer[VMMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamVMMetrics not implemented")
}
func (UnimplementedNodeAgentServer) CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedNodeAgentServer) ApplyNetworkConfig(context.Context, *NetworkConfigRequest) (*NetworkConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNetworkConfig not implemented")
}
func (UnimplementedNodeAgentServer) StartVNCProxy(context.Context, *VNCProxyRequest) (*VNCProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVNCProxy not implemented")
}
func (UnimplementedNodeAgentServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeAgentServer) ImportDisk(context.Context, *DiskImportRequest) (*DiskImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportDisk not implemented")
}
func (UnimplementedNodeAgentServer) BackupDisk(context.Context, *BackupDiskRequest) (*BackupDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupDisk not implemented")
}
func (UnimplementedNodeAgentServer) RestoreDisk(context.Context, *RestoreDiskRequest) (*RestoreDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreDisk not implemented")
}
func (UnimplementedNodeAgentServer) GetLiveMetrics(context.Context, *GetLiveMetricsRequest) (*GetLiveMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiveMetrics not implemented")
}
func (UnimplementedNodeAgentServer) ScanVMs(context.Context, *ScanVMsRequest) (*ScanVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanVMs not implemented")
}
func (UnimplementedNodeAgentServer) CreateStorageVolume(context.Context, *CreateStorageVolumeRequest) (*CreateStorageVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStorageVolume not implemented")
}
func (UnimplementedNodeAgentServer) DeleteStorageVolume(context.Context, *DeleteStorageVolumeRequest) (*DeleteStorageVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStorageVolume not implemented")
}
func (UnimplementedNodeAgentServer) GetStorageReport(context.Context, *GetStorageReportRequest) (*GetStorageReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageReport not implemented")
}
func (UnimplementedNodeAgentServer) MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateVM not implemented")
}
func (UnimplementedNodeAgentServer) SyncTemplate(context.Context, *SyncTemplateRequest) (*SyncTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncTemplate not implemented")
}
func (UnimplementedNodeAgentServer) AttachDisk(context.Context, *AttachDiskRequest) (*AttachDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachDisk not implemented")
}
func (UnimplementedNodeAgentServer) DetachDisk(context.Context, *DetachDiskRequest) (*DetachDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachDisk not implemented")
}
func (UnimplementedNodeAgentServer) DefineNetwork(context.Context, *DefineNetworkRequest) (*DefineNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DefineNetwork not implemented")
}
func (UnimplementedNodeAgentServer) UndefineNetwork(context.Context, *UndefineNetworkRequest) (*UndefineNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndefineNetwork not implemented")
}
func (UnimplementedNodeAgentServer) ProbeIPs(context.Context, *ProbeIPsRequest) (*ProbeIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeIPs not implemented")
}
func (UnimplementedNodeAgentServer) ConfigureFloatingIP(context.Context, *FloatingIPRequest) (*FloatingIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureFloatingIP not implemented")
}
func (UnimplementedNodeAgentServer) ConfigureVPC(context.Context, *VPCRequest) (*VPCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureVPC not implemented")
}
func (UnimplementedNodeAgentServer) SetQuarantine(context.Context, *SetQuarantineRequest) (*SetQuarantineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetQuarantine not implemented")
}
func (UnimplementedNodeAgentServer) SetConsoleAccess(context.Context, *SetConsoleAccessRequest) (*SetConsoleAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConsoleAccess not implemented")
}
func (UnimplementedNodeAgentServer) GetExportProgress(context.Context, *GetExportProgressRequest) (*GetExportProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportProgress not implemented")
}
func (UnimplementedNodeAgentServer) GetGuestConnections(context.Context, *GetGuestConnectionsRequest) (*GetGuestConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGuestConnections not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _NodeAgent_ExecuteVMCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ExecuteVMCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ExecuteVMCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ExecuteVMCommand(ctx, req.(*VMCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetVMStatus(ctx, req.(*VMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StreamVMMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VMMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).StreamVMMetrics(m, &grpc.GenericServerStream[VMMetricsRequest, VMMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamVMMetricsServer = grpc.ServerStreamingServer[VMMetricsResponse]

func _NodeAgent_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ApplyNetworkConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ApplyNetworkConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ApplyNetworkConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ApplyNetworkConfig(ctx, req.(*NetworkConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StartVNCProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VNCProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).StartVNCProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_StartVNCProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).StartVNCProxy(ctx, req.(*VNCProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ImportDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ImportDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ImportDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ImportDisk(ctx, req.(*DiskImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_BackupDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).BackupDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_BackupDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).BackupDisk(ctx, req.(*BackupDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_RestoreDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RestoreDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RestoreDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RestoreDisk(ctx, req.(*RestoreDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetLiveMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiveMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetLiveMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetLiveMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetLiveMetrics(ctx, req.(*GetLiveMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ScanVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ScanVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ScanVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ScanVMs(ctx, req.(*ScanVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_CreateStorageVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStorageVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).CreateStorageVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_CreateStorageVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).CreateStorageVolume(ctx, req.(*CreateStorageVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DeleteStorageVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorageVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DeleteStorageVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DeleteStorageVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DeleteStorageVolume(ctx, req.(*DeleteStorageVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetStorageReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetStorageReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetStorageReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetStorageReport(ctx, req.(*GetStorageReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_MigrateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).MigrateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_MigrateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).MigrateVM(ctx, req.(*MigrateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_SyncTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SyncTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SyncTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SyncTemplate(ctx, req.(*SyncTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_AttachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).AttachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_AttachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).AttachDisk(ctx, req.(*AttachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DetachDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DetachDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DetachDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DetachDisk(ctx, req.(*DetachDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_DefineNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefineNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).DefineNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_DefineNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).DefineNetwork(ctx, req.(*DefineNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UndefineNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndefineNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UndefineNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UndefineNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UndefineNetwork(ctx, req.(*UndefineNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ProbeIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ProbeIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ProbeIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ProbeIPs(ctx, req.(*ProbeIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ConfigureFloatingIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FloatingIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ConfigureFloatingIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ConfigureFloatingIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ConfigureFloatingIP(ctx, req.(*FloatingIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ConfigureVPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ConfigureVPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ConfigureVPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ConfigureVPC(ctx, req.(*VPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_SetQuarantine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQuarantineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SetQuarantine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SetQuarantine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SetQuarantine(ctx, req.(*SetQuarantineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_SetConsoleAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConsoleAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SetConsoleAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SetConsoleAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SetConsoleAccess(ctx, req.(*SetConsoleAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetExportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetExportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetExportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetExportProgress(ctx, req.(*GetExportProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetGuestConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGuestConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetGuestConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetGuestConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetGuestConnections(ctx, req.(*GetGuestConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeAgent_RegisterNode_Handler,
		},
		{
			MethodName: "ExecuteVMCommand",
			Handler:    _NodeAgent_ExecuteVMCommand_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _NodeAgent_GetVMStatus_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _NodeAgent_CreateSnapshot_Handler,
		},
		{
			MethodName: "ApplyNetworkConfig",
			Handler:    _NodeAgent_ApplyNetworkConfig_Handler,
		},
		{
			MethodName: "StartVNCProxy",
			Handler:    _NodeAgent_StartVNCProxy_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeAgent_GetNodeInfo_Handler,
		},
		{
			MethodName: "ImportDisk",
			Handler:    _NodeAgent_ImportDisk_Handler,
		},
		{
			MethodName: "BackupDisk",
			Handler:    _NodeAgent_BackupDisk_Handler,
		},
		{
			MethodName: "RestoreDisk",
			Handler:    _NodeAgent_RestoreDisk_Handler,
		},
		{
			MethodName: "GetLiveMetrics",
			Handler:    _NodeAgent_GetLiveMetrics_Handler,
		},
		{
			MethodName: "ScanVMs",
			Handler:    _NodeAgent_ScanVMs_Handler,
		},
		{
			MethodName: "CreateStorageVolume",
			Handler:    _NodeAgent_CreateStorageVolume_Handler,
		},
		{
			MethodName: "DeleteStorageVolume",
			Handler:    _NodeAgent_DeleteStorageVolume_Handler,
		},
		{
			MethodName: "GetStorageReport",
			Handler:    _NodeAgent_GetStorageReport_Handler,
		},
		{
			MethodName: "MigrateVM",
			Handler:    _NodeAgent_MigrateVM_Handler,
		},
		{
			MethodName: "SyncTemplate",
			Handler:    _NodeAgent_SyncTemplate_Handler,
		},
		{
			MethodName: "AttachDisk",
			Handler:    _NodeAgent_AttachDisk_Handler,
		},
		{
			MethodName: "DetachDisk",
			Handler:    _NodeAgent_DetachDisk_Handler,
		},
		{
			MethodName: "DefineNetwork",
			Handler:    _NodeAgent_DefineNetwork_Handler,
		},
		{
			MethodName: "UndefineNetwork",
			Handler:    _NodeAgent_UndefineNetwork_Handler,
		},
		{
			MethodName: "ProbeIPs",
			Handler:    _NodeAgent_ProbeIPs_Handler,
		},
		{
			MethodName: "ConfigureFloatingIP",
			Handler:    _NodeAgent_ConfigureFloatingIP_Handler,
		},
		{
			MethodName: "ConfigureVPC",
			Handler:    _NodeAgent_ConfigureVPC_Handler,
		},
		{
			MethodName: "SetQuarantine",
			Handler:    _NodeAgent_SetQuarantine_Handler,
		},
		{
			MethodName: "SetConsoleAccess",
			Handler:    _NodeAgent_SetConsoleAccess_Handler,
		},
		{
			MethodName: "GetExportProgress",
			Handler:    _NodeAgent_GetExportProgress_Handler,
		},
		{
			MethodName: "GetGuestConnections",
			Handler:    _NodeAgent_GetGuestConnections_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _NodeAgent_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamVMMetrics",
			Handler:       _NodeAgent_StreamVMMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/agent.proto",
}
