"use client"

import { useState } from "react"
import { useParams, useRouter } from "next/navigation"
import Link from "next/link"
import { 
  Play, Square, RotateCcw, Trash2, RefreshCw, ArrowLeft,
  Eye, EyeOff, Copy, Check, Cpu, MemoryStick, HardDrive,
  Monitor, Server, Network, Database, Shield, FileText, Terminal, Activity, ExternalLink
} from "lucide-react"
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, AreaChart, Area } from "recharts"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

const mockVM = {
  id: "vm-001", name: "web-server-01", status: "running" as const, node: "node-02", osTemplate: "Ubuntu 22.04 LTS",
  cpu: { cores: 4, usage: 65 }, ram: { total: 8, used: 5.2 }, disk: { total: 100, used: 42 },
  ipAddress: "192.168.1.101", vncPort: 5901, vncPassword: "xK9mP2vL8nQ", createdAt: "2024-01-15T10:30:00Z", lastActivity: "2024-01-20T14:22:00Z",
}

const cpuData = [{ time: "00:00", value: 45 }, { time: "04:00", value: 32 }, { time: "08:00", value: 78 }, { time: "12:00", value: 65 }, { time: "16:00", value: 89 }, { time: "20:00", value: 55 }, { time: "24:00", value: 42 }]
const memoryData = [{ time: "00:00", value: 4.2 }, { time: "04:00", value: 3.8 }, { time: "08:00", value: 5.5 }, { time: "12:00", value: 6.2 }, { time: "16:00", value: 5.8 }, { time: "20:00", value: 5.2 }, { time: "24:00", value: 4.9 }]
const networkData = [{ time: "00:00", in: 12, out: 8 }, { time: "04:00", in: 5, out: 3 }, { time: "08:00", in: 45, out: 32 }, { time: "12:00", in: 38, out: 25 }, { time: "16:00", in: 62, out: 48 }, { time: "20:00", in: 28, out: 18 }, { time: "24:00", in: 15, out: 10 }]
const templates = [
  { id: "ubuntu-2204", name: "Ubuntu 22.04 LTS", icon: "🐧" }, { id: "ubuntu-2004", name: "Ubuntu 20.04 LTS", icon: "🐧" },
  { id: "debian-11", name: "Debian 11 Bullseye", icon: "🦄" }, { id: "centos-8", name: "CentOS Stream 8", icon: "🔴" },
  { id: "almalinux-8", name: "AlmaLinux 8", icon: "🔵" }, { id: "rocky-9", name: "Rocky Linux 9", icon: "🪨" },
]

function formatDate(dateString: string) { return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) }
function formatRelativeTime(dateString: string) {
  const date = new Date(dateString), now = new Date(), diffMs = now.getTime() - date.getTime(), diffMins = Math.floor(diffMs / 60000), diffHours = Math.floor(diffMins / 60), diffDays = Math.floor(diffHours / 24)
  if (diffMins < 60) return `${diffMins} minutes ago`
  if (diffHours < 24) return `${diffHours} hours ago`
  return `${diffDays} days ago`
}

function ProgressBar({ value, max, label, color = "primary" }: { value: number; max: number; label: string; color?: "primary" | "secondary" | "accent" | "success" | "danger" }) {
  const percentage = Math.round((value / max) * 100)
  const colorClasses = { primary: "bg-primary", secondary: "bg-secondary", accent: "bg-accent", success: "bg-success", danger: "bg-danger" }
  return (
    <div className="mb-4">
      <div className="flex justify-between items-center mb-1"><span className="text-xs font-bold uppercase text-gray-600">{label}</span><span className="text-xs font-black">{value} / {max} ({percentage}%)</span></div>
      <div className="h-4 bg-gray-200 border-2 border-black relative"><div className={`h-full ${colorClasses[color]} transition-all duration-300`} style={{ width: `${percentage}%` }} /></div>
    </div>
  )
}

function StatusBadge({ status }: { status: string }) {
  const statusConfig: Record<string, { bg: string; text: string; label: string }> = {
    running: { bg: "bg-success", text: "text-black", label: "Running" }, stopped: { bg: "bg-gray-400", text: "text-white", label: "Stopped" },
    paused: { bg: "bg-warning", text: "text-black", label: "Paused" }, error: { bg: "bg-danger", text: "text-white", label: "Error" }, building: { bg: "bg-secondary", text: "text-black", label: "Building" },
  }
  const config = statusConfig[status] || statusConfig.stopped
  return <span className={`inline-flex items-center px-3 py-1 border-2 border-black text-xs font-bold uppercase shadow-neo-sm ${config.bg} ${config.text}`}><span className={`w-2 h-2 mr-2 border border-black ${status === 'running' ? 'bg-black animate-pulse' : 'bg-black/30'}`}></span>{config.label}</span>
}

export default function VMDetailPage() {
  const params = useParams(), router = useRouter()
  const [showPassword, setShowPassword] = useState(false), [copied, setCopied] = useState(false)
  const [rebuildDialogOpen, setRebuildDialogOpen] = useState(false), [deleteDialogOpen, setDeleteDialogOpen] = useState(false)
  const [selectedTemplate, setSelectedTemplate] = useState(""), [confirmVMName, setConfirmVMName] = useState(""), [actionLoading, setActionLoading] = useState<string | null>(null)
  const vmId = params.id as string, vm = { ...mockVM, id: vmId, name: vmId === "vm-001" ? "web-server-01" : vmId.replace(/-/g, " ") }

  const handleAction = async (action: string) => { setActionLoading(action); await new Promise(resolve => setTimeout(resolve, 1000)); setActionLoading(null) }
  const copyToClipboard = (text: string) => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000) }
  const handleRebuild = () => { if (confirmVMName === vm.name && selectedTemplate) { setRebuildDialogOpen(false); setConfirmVMName(""); setSelectedTemplate("") } }
  const handleDelete = () => { setDeleteDialogOpen(false); router.push("/vms") }

  return (
    <div className="max-w-7xl mx-auto">
      <nav className="flex items-center gap-2 mb-6"><Link href="/vms" className="flex items-center gap-2 text-sm font-bold uppercase text-gray-500 hover:text-black transition-colors"><ArrowLeft className="w-4 h-4" />Back to VMs</Link></nav>
      <div className="bg-white border-4 border-black p-6 shadow-neo mb-6">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 bg-primary flex items-center justify-center border-4 border-black shadow-neo"><Monitor className="w-8 h-8" /></div>
            <div><h1 className="text-2xl lg:text-3xl font-black uppercase tracking-tight text-black">{vm.name}</h1><div className="flex items-center gap-3 mt-2"><StatusBadge status={vm.status} /><span className="text-xs font-medium text-gray-500">ID: {vm.id}</span></div></div>
          </div>
          <div className="flex flex-wrap gap-3">
            {vm.status === "running" ? (<><Button variant="secondary" size="sm" onClick={() => handleAction("stop")} disabled={actionLoading !== null}>{actionLoading === "stop" ? <RotateCcw className="w-4 h-4 animate-spin" /> : <Square className="w-4 h-4" />}Stop</Button><Button variant="secondary" size="sm" onClick={() => handleAction("restart")} disabled={actionLoading !== null}>{actionLoading === "restart" ? <RotateCcw className="w-4 h-4 animate-spin" /> : <RotateCcw className="w-4 h-4" />}Restart</Button></>) : (<Button variant="default" size="sm" onClick={() => handleAction("start")} disabled={actionLoading !== null}>{actionLoading === "start" ? <RotateCcw className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4" />}Start</Button>)}
            <Dialog open={rebuildDialogOpen} onOpenChange={setRebuildDialogOpen}><DialogTrigger><Button variant="secondary" size="sm"><RefreshCw className="w-4 h-4" />Rebuild</Button></DialogTrigger><DialogContent className="max-w-md border-4 border-black shadow-neo-xl"><DialogHeader><DialogTitle className="text-lg font-black uppercase">Rebuild VM</DialogTitle><DialogDescription className="text-sm text-gray-600">This will destroy the current VM and create a new one from a template. All data will be lost.</DialogDescription></DialogHeader><div className="space-y-4 py-4"><div><span className="text-xs font-bold uppercase text-gray-600 mb-2 block">Select Template</span><div className="grid grid-cols-2 gap-2">{templates.map((t) => (<button key={t.id} type="button" onClick={() => setSelectedTemplate(t.id)} className={`p-3 border-2 border-black text-left transition-all ${selectedTemplate === t.id ? "bg-primary shadow-neo" : "bg-white hover:bg-gray-50"}`}><span className="text-lg">{t.icon}</span><span className="text-xs font-bold uppercase block mt-1">{t.name}</span></button>))}</div></div><div className="bg-danger/10 border-2 border-danger p-4"><p className="text-xs font-bold text-danger uppercase mb-2">Warning: Data Loss</p><p className="text-xs text-gray-700">All data on this VM will be permanently deleted.</p></div><div><span className="text-xs font-bold uppercase text-gray-600 mb-2 block">Type <span className="font-black">{vm.name}</span> to confirm</span><Input id="confirm-vm-name" value={confirmVMName} onChange={(e) => setConfirmVMName(e.target.value)} placeholder="Enter VM name" className="border-2 border-black" /></div></div><DialogFooter><Button variant="ghost" onClick={() => setRebuildDialogOpen(false)}>Cancel</Button><Button variant="destructive" disabled={confirmVMName !== vm.name || !selectedTemplate} onClick={handleRebuild}><Trash2 className="w-4 h-4" />Rebuild VM</Button></DialogFooter></DialogContent></Dialog>
            <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}><DialogTrigger><Button variant="destructive" size="sm"><Trash2 className="w-4 h-4" />Delete</Button></DialogTrigger><DialogContent className="max-w-md border-4 border-black shadow-neo-xl"><DialogHeader><DialogTitle className="text-lg font-black uppercase">Delete VM</DialogTitle><DialogDescription className="text-sm text-gray-600">Are you sure you want to delete this VM?</DialogDescription></DialogHeader><div className="bg-danger/10 border-2 border-danger p-4"><p className="text-xs font-bold text-danger uppercase mb-2">Permanent Data Loss</p><p className="text-xs text-gray-700">The VM "{vm.name}" will be permanently deleted.</p></div><DialogFooter><Button variant="ghost" onClick={() => setDeleteDialogOpen(false)}>Cancel</Button><Button variant="destructive" onClick={handleDelete}><Trash2 className="w-4 h-4" />Delete VM</Button></DialogFooter></DialogContent></Dialog>
          </div>
        </div>
      </div>
      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList className="bg-white border-2 border-black p-1 shadow-neo-sm inline-flex flex-wrap"><TabsTrigger value="overview" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><Monitor className="w-4 h-4 mr-2" />Overview</TabsTrigger><TabsTrigger value="console" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><Terminal className="w-4 h-4 mr-2" />Console</TabsTrigger><TabsTrigger value="network" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><Network className="w-4 h-4 mr-2" />Network</TabsTrigger><TabsTrigger value="snapshots" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><Database className="w-4 h-4 mr-2" />Snapshots</TabsTrigger><TabsTrigger value="backups" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><HardDrive className="w-4 h-4 mr-2" />Backups</TabsTrigger><TabsTrigger value="firewall" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><Shield className="w-4 h-4 mr-2" />Firewall</TabsTrigger><TabsTrigger value="logs" className="data-[selected]:bg-primary data-[selected]:shadow-neo"><FileText className="w-4 h-4 mr-2" />Logs</TabsTrigger></TabsList>
        <TabsContent value="overview" className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 bg-white border-4 border-black p-6 shadow-neo"><h2 className="text-lg font-black uppercase tracking-tight text-black mb-6 flex items-center gap-2"><Activity className="w-5 h-5" />Resource Usage</h2><div className="space-y-6"><ProgressBar value={vm.cpu.usage} max={100} label="CPU" color={vm.cpu.usage > 80 ? "danger" : "primary"} /><ProgressBar value={vm.ram.used} max={vm.ram.total} label="Memory" color={vm.ram.used / vm.ram.total > 0.8 ? "danger" : "secondary"} /><ProgressBar value={vm.disk.used} max={vm.disk.total} label="Disk" color={vm.disk.used / vm.disk.total > 0.8 ? "danger" : "accent"} /></div></div>
            <div className="bg-white border-4 border-black p-6 shadow-neo"><h2 className="text-lg font-black uppercase tracking-tight text-black mb-6 flex items-center gap-2"><Server className="w-5 h-5" />VM Details</h2><div className="space-y-4"><div className="flex items-center justify-between pb-3 border-b-2 border-black"><span className="text-xs font-bold uppercase text-gray-500">Node</span><span className="text-sm font-black">{vm.node}</span></div><div className="flex items-center justify-between pb-3 border-b-2 border-black"><span className="text-xs font-bold uppercase text-gray-500">OS Template</span><span className="text-sm font-black">{vm.osTemplate}</span></div><div className="flex items-center justify-between pb-3 border-b-2 border-black"><span className="text-xs font-bold uppercase text-gray-500">IP Address</span><span className="text-sm font-black font-mono">{vm.ipAddress}</span></div><div className="flex items-center justify-between pb-3 border-b-2 border-black"><span className="text-xs font-bold uppercase text-gray-500">Created</span><span className="text-sm font-medium">{formatDate(vm.createdAt)}</span></div><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase text-gray-500">Last Activity</span><span className="text-sm font-medium">{formatRelativeTime(vm.lastActivity)}</span></div></div></div>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="bg-white border-4 border-black p-6 shadow-neo"><h3 className="text-sm font-black uppercase tracking-tight text-black mb-4 flex items-center gap-2"><Cpu className="w-4 h-4" />CPU Usage (24h)</h3><div className="h-48"><ResponsiveContainer width="100%" height="100%"><AreaChart data={cpuData}><defs><linearGradient id="cpuGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#FFE500" stopOpacity={0.8}/><stop offset="95%" stopColor="#FFE500" stopOpacity={0.1}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#000" strokeOpacity={0.1} /><XAxis dataKey="time" stroke="#000" fontSize={10} tickLine={false} axisLine={false} /><YAxis stroke="#000" fontSize={10} tickLine={false} axisLine={false} domain={[0, 100]} tickFormatter={(v) => `${v}%`} /><Tooltip contentStyle={{ backgroundColor: "#fff", border: "2px solid #000", borderRadius: 0, fontSize: "12px", fontWeight: "bold" }} formatter={(v) => [`${v}%`, "CPU"]} /><Area type="monotone" dataKey="value" stroke="#000" strokeWidth={2} fill="url(#cpuGradient)" /></AreaChart></ResponsiveContainer></div></div>
            <div className="bg-white border-4 border-black p-6 shadow-neo"><h3 className="text-sm font-black uppercase tracking-tight text-black mb-4 flex items-center gap-2"><MemoryStick className="w-4 h-4" />Memory Usage (24h)</h3><div className="h-48"><ResponsiveContainer width="100%" height="100%"><AreaChart data={memoryData}><defs><linearGradient id="memGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#00F0FF" stopOpacity={0.8}/><stop offset="95%" stopColor="#00F0FF" stopOpacity={0.1}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#000" strokeOpacity={0.1} /><XAxis dataKey="time" stroke="#000" fontSize={10} tickLine={false} axisLine={false} /><YAxis stroke="#000" fontSize={10} tickLine={false} axisLine={false} domain={[0, vm.ram.total]} tickFormatter={(v) => `${v}GB`} /><Tooltip contentStyle={{ backgroundColor: "#fff", border: "2px solid #000", borderRadius: 0, fontSize: "12px", fontWeight: "bold" }} formatter={(v) => [`${v} GB`, "Memory"]} /><Area type="monotone" dataKey="value" stroke="#000" strokeWidth={2} fill="url(#memGradient)" /></AreaChart></ResponsiveContainer></div></div>
            <div className="bg-white border-4 border-black p-6 shadow-neo"><h3 className="text-sm font-black uppercase tracking-tight text-black mb-4 flex items-center gap-2"><Network className="w-4 h-4" />Network I/O (24h)</h3><div className="h-48"><ResponsiveContainer width="100%" height="100%"><LineChart data={networkData}><CartesianGrid strokeDasharray="3 3" stroke="#000" strokeOpacity={0.1} /><XAxis dataKey="time" stroke="#000" fontSize={10} tickLine={false} axisLine={false} /><YAxis stroke="#000" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(v) => `${v}MB`} /><Tooltip contentStyle={{ backgroundColor: "#fff", border: "2px solid #000", borderRadius: 0, fontSize: "12px", fontWeight: "bold" }} formatter={(v, n) => [`${v} MB/s`, n === "in" ? "Download" : "Upload"]} /><Line type="monotone" dataKey="in" stroke="#00F0FF" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="out" stroke="#FF00A0" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div><div className="flex justify-center gap-4 mt-2"><div className="flex items-center gap-1"><div className="w-3 h-3 bg-secondary"></div><span className="text-xs font-bold">Download</span></div><div className="flex items-center gap-1"><div className="w-3 h-3 bg-accent"></div><span className="text-xs font-bold">Upload</span></div></div></div>
          </div>
          <div className="bg-white border-4 border-black p-6 shadow-neo"><h2 className="text-lg font-black uppercase tracking-tight text-black mb-6 flex items-center gap-2"><Monitor className="w-5 h-5" />VNC Access</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><div><span className="text-xs font-bold uppercase text-gray-500 block mb-1">VNC Port</span><div className="flex items-center gap-2"><span className="text-xl font-black font-mono">{vm.vncPort}</span><Button variant="ghost" size="icon-sm" onClick={() => copyToClipboard(vm.vncPort.toString())}>{copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}</Button></div></div><div><span className="text-xs font-bold uppercase text-gray-500 block mb-1">VNC Password</span><div className="flex items-center gap-2"><span className="text-xl font-black font-mono">{showPassword ? vm.vncPassword : "••••••••••"}</span><Button variant="ghost" size="icon-sm" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</Button><Button variant="ghost" size="icon-sm" onClick={() => copyToClipboard(vm.vncPassword)}>{copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}</Button></div></div><div className="flex items-end"><Button variant="accent" className="w-full"><ExternalLink className="w-4 h-4" />Open VNC Console</Button></div></div></div>
        </TabsContent>
        <TabsContent value="console"><div className="bg-white border-4 border-black p-6 shadow-neo"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-black uppercase tracking-tight text-black flex items-center gap-2"><Terminal className="w-5 h-5" />Console</h2><Button variant="secondary" size="sm"><ExternalLink className="w-4 h-4 mr-2" />Open in New Tab</Button></div><div className="bg-black border-4 border-black p-4 h-96 font-mono text-sm text-green-400 overflow-auto"><pre className="whitespace-pre-wrap">{"MaburVM Console - " + vm.name + "\n"}{"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"}{"Last login: " + formatDate(vm.lastActivity) + " from 192.168.1.50\n\n"}{"user@" + vm.name + ":~$ uptime\n"}{" " + new Date().toLocaleTimeString() + " up 5 days, 12:34, 2 users, load average: 0.65, 0.72, 0.68\n\n"}{"user@" + vm.name + ":~$ free -h\n"}{"              total        used        free      shared  buff/cache   available\n"}{"Mem:           8Gi       5.2Gi       2.1Gi       123Mi       678Mi       2.5Gi\n"}{"Swap:         512Mi          0B       512Mi\n\n"}{"user@" + vm.name + ":~$ "}<span className="animate-pulse">_</span></pre></div></div></TabsContent>
        <TabsContent value="network"><div className="bg-white border-4 border-black p-6 shadow-neo"><h2 className="text-lg font-black uppercase tracking-tight text-black mb-6 flex items-center gap-2"><Network className="w-5 h-5" />Network Configuration</h2><div className="space-y-4"><div className="flex items-center justify-between p-4 bg-gray-50 border-2 border-black"><div><span className="text-xs font-bold uppercase text-gray-500 block">Primary IP</span><span className="text-xl font-black font-mono">{vm.ipAddress}</span></div><span className="neo-badge-primary">Active</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><div className="p-4 border-2 border-black"><span className="text-xs font-bold uppercase text-gray-500 block">Gateway</span><span className="text-sm font-mono">192.168.1.1</span></div><div className="p-4 border-2 border-black"><span className="text-xs font-bold uppercase text-gray-500 block">Netmask</span><span className="text-sm font-mono">255.255.255.0</span></div><div className="p-4 border-2 border-black"><span className="text-xs font-bold uppercase text-gray-500 block">DNS Primary</span><span className="text-sm font-mono">8.8.8.8</span></div><div className="p-4 border-2 border-black"><span className="text-xs font-bold uppercase text-gray-500 block">DNS Secondary</span><span className="text-sm font-mono">8.8.4.4</span></div></div></div></div></TabsContent>
        <TabsContent value="snapshots"><div className="bg-white border-4 border-black p-6 shadow-neo"><div className="flex items-center justify-between mb-6"><h2 className="text-lg font-black uppercase tracking-tight text-black flex items-center gap-2"><Database className="w-5 h-5" />Snapshots</h2><Button variant="default" size="sm"><RefreshCw className="w-4 h-4 mr-2" />Create Snapshot</Button></div><div className="space-y-3">{[{ id: "snap-001", name: "before-update", date: "2024-01-18", size: "15 GB" }, { id: "snap-002", name: "baseline", date: "2024-01-15", size: "42 GB" }].map((snap) => (<div key={snap.id} className="flex items-center justify-between p-4 border-2 border-black hover:bg-gray-50"><div className="flex items-center gap-4"><Database className="w-5 h-5" /><div><span className="font-black">{snap.name}</span><span className="text-xs text-gray-500 ml-2">{snap.date}</span></div></div><div className="flex items-center gap-3"><span className="text-xs font-bold">{snap.size}</span><Button variant="ghost" size="sm">Restore</Button><Button variant="ghost" size="sm">Delete</Button></div></div>))}</div></div></TabsContent>
        <TabsContent value="backups"><div className="bg-white border-4 border-black p-6 shadow-neo"><div className="flex items-center justify-between mb-6"><h2 className="text-lg font-black uppercase tracking-tight text-black flex items-center gap-2"><HardDrive className="w-5 h-5" />Backups</h2><Button variant="default" size="sm"><RefreshCw className="w-4 h-4 mr-2" />Create Backup</Button></div><div className="space-y-3">{[{ id: "backup-001", name: "daily-2024-01-20", date: "2024-01-20", size: "38 GB", status: "completed" }, { id: "backup-002", name: "weekly-2024-01-14", date: "2024-01-14", size: "40 GB", status: "completed" }, { id: "backup-003", name: "monthly-2024-01-01", date: "2024-01-01", size: "42 GB", status: "completed" }].map((backup) => (<div key={backup.id} className="flex items-center justify-between p-4 border-2 border-black hover:bg-gray-50"><div className="flex items-center gap-4"><HardDrive className="w-5 h-5" /><div><span className="font-black">{backup.name}</span><span className="text-xs text-gray-500 ml-2">{backup.date}</span></div></div><div className="flex items-center gap-3"><span className="text-xs font-bold">{backup.size}</span><span className="neo-badge-success text-[10px]">{backup.status}</span><Button variant="ghost" size="sm">Restore</Button><Button variant="ghost" size="sm">Download</Button></div></div>))}</div></div></TabsContent>
        <TabsContent value="firewall"><div className="bg-white border-4 border-black p-6 shadow-neo"><div className="flex items-center justify-between mb-6"><h2 className="text-lg font-black uppercase tracking-tight text-black flex items-center gap-2"><Shield className="w-5 h-5" />Firewall Rules</h2><Button variant="default" size="sm"><RefreshCw className="w-4 h-4 mr-2" />Add Rule</Button></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b-4 border-black"><th className="text-left py-3 px-4 text-xs font-black uppercase">Protocol</th><th className="text-left py-3 px-4 text-xs font-black uppercase">Port</th><th className="text-left py-3 px-4 text-xs font-black uppercase">Source</th><th className="text-left py-3 px-4 text-xs font-black uppercase">Action</th><th className="text-left py-3 px-4 text-xs font-black uppercase">Status</th><th className="text-left py-3 px-4 text-xs font-black uppercase">Actions</th></tr></thead><tbody>{[{ proto: "TCP", port: "22", source: "Any", action: "Allow", status: "active" }, { proto: "TCP", port: "80", source: "Any", action: "Allow", status: "active" }, { proto: "TCP", port: "443", source: "Any", action: "Allow", status: "active" }, { proto: "TCP", port: "3389", source: "192.168.1.0/24", action: "Allow", status: "active" }].map((rule) => (<tr key={rule.port} className="border-b-2 border-black"><td className="py-3 px-4 font-mono text-sm">{rule.proto}</td><td className="py-3 px-4 font-mono text-sm">{rule.port}</td><td className="py-3 px-4 font-mono text-sm">{rule.source}</td><td className="py-3 px-4"><span className="neo-badge-success">{rule.action}</span></td><td className="py-3 px-4"><span className="w-2 h-2 inline-block bg-success mr-2"></span>{rule.status}</td><td className="py-3 px-4"><Button variant="ghost" size="sm">Edit</Button><Button variant="ghost" size="sm">Delete</Button></td></tr>))}</tbody></table></div></div></TabsContent>
        <TabsContent value="logs"><div className="bg-white border-4 border-black p-6 shadow-neo"><h2 className="text-lg font-black uppercase tracking-tight text-black mb-6 flex items-center gap-2"><FileText className="w-5 h-5" />VM Logs</h2><div className="bg-black border-4 border-black p-4 h-96 font-mono text-xs text-green-400 overflow-auto"><pre className="whitespace-pre-wrap">{"[2024-01-20 14:22:15] INFO: VM heartbeat received\n"}{"[2024-01-20 14:20:15] INFO: VM heartbeat received\n"}{"[2024-01-20 14:15:00] INFO: Backup started: daily-2024-01-20\n"}{"[2024-01-20 14:22:00] INFO: Backup completed: 38.2 GB in 7m 44s\n"}{"[2024-01-20 10:30:00] WARN: High CPU usage detected: 92%\n"}{"[2024-01-20 10:35:00] INFO: CPU usage normalized: 65%\n"}{"[2024-01-20 08:00:00] INFO: VM started\n"}{"[2024-01-19 22:00:00] INFO: VM stopped by user admin\n"}{"[2024-01-19 18:30:00] INFO: Firewall rule added: TCP 3389 from 192.168.1.0/24\n"}{"[2024-01-15 10:30:00] INFO: VM created from template: Ubuntu 22.04 LTS\n"}</pre></div></div></TabsContent>
      </Tabs>
    </div>
  )
}